# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ddc362da271f619245c2721ac5f593a57d8bd39121193e7dcc39b1ce391c53248477be41291a792d86dbcd4094c061824ea2138f4e19343bd2d999e8ec0f01

test:
  secret_key_base: 7c580ab4fab7a6353b4995a4ec6a61a4112e00537311ce8c8c2a6909374670fb9f4eaf0c92da2baf0583b3dbb2a4d7a9944b9387230255c44a975b7ef93c2c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
